esphome:
  name: "victron-scanner"

external_components:
  - source: github://Fabian-Schmidt/esphome-victron_ble

esp32:
  board: esp32dev

logger:
  level: INFO

esp32_ble_tracker:

victron_scanner:
